Numpy

In [ ]:
import numpy as np

In [ ]:
kohli_runs=np.array([45,72,33,61,88,54,40,76,92,58])
print(kohli_runs)

[45 72 33 61 88 54 40 76 92 58]


In [ ]:
type(kohli_runs)

numpy.ndarray

In [ ]:
kohli_runs.shape

(10,)

In [ ]:
batters=np.array([[45,72,33,61,88],[55,48,70,92,60],[30,44,50,78,81]])
print(batters)

[[45 72 33 61 88]
 [55 48 70 92 60]
 [30 44 50 78 81]]


In [ ]:
batters.shape

(3, 5)

In [ ]:
batters.ndim

2

In [ ]:
batters.dtype

dtype('int64')

In [ ]:
batters.size

15

In [ ]:
batters.nbytes

120

In [ ]:
kohli_runs[0]

np.int64(45)

In [ ]:
kohli_runs[-3:]

array([76, 92, 58])

In [ ]:
batters[1][2]

np.int64(70)

In [ ]:
runs=np.array([45,72,33,61,88,54])
runs.reshape(2,3)

array([[45, 72, 33],
       [61, 88, 54]])

In [ ]:
kohli_runs+10

array([ 55,  82,  43,  71,  98,  64,  50,  86, 102,  68])

In [ ]:
kohli_runs*2

array([ 90, 144,  66, 122, 176, 108,  80, 152, 184, 116])

In [ ]:
np.sum(kohli_runs)

np.int64(619)

In [ ]:
np.mean(kohli_runs)

np.float64(61.9)

In [ ]:
np.max(kohli_runs)

np.int64(92)

In [ ]:
np.min(kohli_runs)

np.int64(33)

In [ ]:
np.median(kohli_runs)

np.float64(59.5)

In [ ]:
np.std(kohli_runs)

np.float64(18.886238376129853)

In [ ]:
kohli=np.array([45,72,33,61,88])
gill=np.array([55,48,70,92,60])
print(np.mean(kohli))
print(np.mean(gill))

59.8
65.0


In [ ]:
kohli>50

array([False,  True, False,  True,  True])

In [ ]:
kohli[kohli>50]

array([72, 61, 88])

In [ ]:
toss_win=np.array([1,0,1,1,0,1,0,1])
np.sum(toss_win)

np.int64(5)

In [ ]:
economy=np.array([6.5,7.1,8.2,5.8,7.4])
np.min(economy)

np.float64(5.8)

In [ ]:
scores=np.array([[180,175,190],[165,200,210],[150,185,170]])
print(scores)

[[180 175 190]
 [165 200 210]
 [150 185 170]]


In [ ]:
np.mean(scores,axis=1)

array([181.66666667, 191.66666667, 168.33333333])

In [ ]:
np.mean(scores,axis=0)

array([165.        , 186.66666667, 190.        ])

In [ ]:
kohli_runs=np.array([45,72,33,61,88,54,40,76,92,58])
avg_runs=np.mean(kohli_runs)
print('Averahe:',avg_runs)
if avg_runs>50:
  print('Player is in Form')
else:
  print('Player is Not in Form')

Averahe: 61.9
Player is in Form


In [ ]:
total_runs =np.sum(kohli_runs[-7::])
print(total_runs)

469


In [ ]:
avrage_runs=np.average(kohli_runs[-7::])
print(avrage_runs)

67.0


In [ ]:
highest_score =np.max(kohli_runs[-7::])
print(highest_score)

92


In [ ]:
lowest_score_kohli=np.min(kohli_runs)
print(lowest_score_kohli)

33


In [14]:
virat_runs =np.array([45,72,33,61,88,54,40,76,92,58])
rohit_runs=np.array([55,70,30,80,93,36,45,90,68,42])

rohit_total=np.sum(rohit_runs)
kohli_total=np.sum(virat_runs)

print("virat Total Runs:",kohli_total)
print("Rohit Total Runs:",rohit_total)

if kohli_total > rohit_total:
    print("Virat Kohli scored more total runs")

elif rohit_total > kohli_total:
    print("Rohit scored more total runs")
else:
    print("Both scored equal total runs")

kohli_avg=np.mean(kohli_runs)
rohit_avg=np.mean(rohit_runs)

avg_diff =abs(kohli_avg-rohit_avg)

print("Kohli Average:", kohli_avg)
print("Rohit Average:",rohit_avg)

print("Difference in Average Runs:",avg_diff)

kohli_better_matches =np.sum(kohli_runs>rohit_runs)

print("Matches where kohli scored more than Rohit:",kohli_better_matches)


virat Total Runs: 619
Rohit Total Runs: 609
Virat Kohli scored more total runs
Kohli Average: 61.9
Rohit Average: 60.9
Difference in Average Runs: 1.0
Matches where kohli scored more than Rohit: 5


In [15]:
team_runs=np.array([[45,60,30],[50,70,40],[20,30,50],[60,40,80],[30,20,40]])

batter_totals =np.sum(team_runs,axis=1)
print("Total Runs of Each Batter:")
print(batter_totals)

match_totals =np.sum(team_runs,axis=0)
print("Match wise Team Totals:")
print(match_totals)

best_batter =np.argmax(batter_totals)+1

print("Beast Performing Batter: Batter",best_batter)
print("Runs:",batter_totals[best_batter-1])

Total Runs of Each Batter:
[135 160 100 180  90]
Match wise Team Totals:
[205 220 240]
Beast Performing Batter: Batter 4
Runs: 180


In [17]:
scores =np.array([45,72,33,61,88,54,40,76,92,58])

mean_scores =np.mean(scores)


variance =np.var(scores)

std_dev=np.std(scores)

print("Mean:",mean_scores)
print("Variance:",variance)
print("standard Deviation:",std_dev)

if std_dev <20:
    print("Player is Consistent")
else:

    print("Player is Inconsistent")

Mean: 61.9
Variance: 356.69
standard Deviation: 18.886238376129853
Player is Consistent


In [21]:
runs =np.array([1,4,0,6,2,1,4,0,1,6,2,1])

total_runs =np.sum(runs)

boundary_runs = np.sum(runs[(runs == 4) | (runs == 6)])

boundary_percentage=(boundary_runs / total_runs)*100

print("Total Runs:",total_runs)
print("Boundary Runs:",boundary_runs)
print("Percentage of Runs through Boundaries:",round(boundary_percentage,2))


print()

Total Runs: 28
Boundary Runs: 20
Percentage of Runs through Boundaries: 71.43

